plugins {
  id 'java'
}

repositories {
  mavenCentral()
}

java {
  sourceCompatibility = JavaVersion.VERSION_11
  targetCompatibility = JavaVersion.VERSION_11
}

// JUnit 4 and TestNG, both on the class path of the tests.
dependencies {
  testImplementation 'junit:junit:4.13.2'
  testImplementation 'org.testng:testng:7.5.1'
}
