package io.github.lnds.kalku;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.StringReader;
import javax.xml.parsers.DocumentBuilderFactory;
import org.junit.jupiter.api.Test;
import org.w3c.dom.Element;
import org.xml.sax.InputSource;

/**
 * What Maven writes as the resolved project is not always XML. Both shapes below came out of
 * a real project's build (Apache Commons CLI), not out of imagination.
 */
class MavenTest {
  private static Element parsed(String text) throws Exception {
    return DocumentBuilderFactory.newInstance()
        .newDocumentBuilder()
        .parse(new InputSource(new StringReader(Maven.readable(text))))
        .getDocumentElement();
  }

  @Test
  void aSecondXmlDeclarationInTheMiddleIsLeftOut() throws Exception {
    String written =
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            + "<!-- Generated by Maven Help Plugin -->\n"
            + "<!-- Effective POM for project 'a:b:jar:1' -->\n"
            + "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            + "<project><packaging>jar</packaging></project>\n";
    assertEquals("project", parsed(written).getTagName());
  }

  @Test
  void aPropertyWhoseNameIsNotAnElementsIsLeftOutAndItsNeighboursKept() throws Exception {
    String written =
        "<?xml version=\"1.0\"?>\n<project><properties>\n"
            + "  <maven.compiler.release>11</maven.compiler.release>\n"
            + "  <javaTarget.qualifier></javaTarget.qualifier>\n"
            + "  <javaTarget.qualifier?></javaTarget.qualifier?>\n"
            + "  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>\n"
            + "</properties></project>\n";
    Element properties = (Element) parsed(written).getElementsByTagName("properties").item(0);
    assertEquals(
        "11", properties.getElementsByTagName("maven.compiler.release").item(0).getTextContent());
    assertEquals(
        "UTF-8",
        properties.getElementsByTagName("project.build.sourceEncoding").item(0).getTextContent());
  }

  @Test
  void whatIsAlreadyXmlIsNotTouched() {
    String written =
        "<?xml version=\"1.0\"?>\n<project xmlns:xsi=\"x\" xsi:schemaLocation=\"a b\">\n"
            + "  <!-- a < b, a > b -->\n  <a.b-c_d>1 &lt; 2</a.b-c_d>\n  <empty/>\n</project>\n";
    assertEquals(written, Maven.readable(written));
  }
}
