#!/bin/sh
# Writes the Homebrew formula for a release, on stdout.
#
#   sh tools/brew-formula.sh <version> <dir-with-tarballs-and-sha256>
#
# The checksums come from the files being released, never from a hand
# that could copy the wrong one: a formula whose sha256 does not match
# the tarball fails at install time, on the user's machine.
set -eu

version="${1:?usage: brew-formula.sh <version> <dist-dir>}"
dist="${2:?usage: brew-formula.sh <version> <dist-dir>}"

sha_of() {
  file="$dist/kalku-v$version-$1.tar.gz.sha256"
  [ -f "$file" ] || { echo "missing $file" >&2; exit 1; }
  # The line is "<sha256>  <filename>", from sha256sum or shasum alike.
  awk '{print $1; exit}' "$file"
}

darwin_arm64="$(sha_of darwin-arm64)"
linux_x86_64="$(sha_of linux-x86_64)"
base="https://github.com/lnds/kalku/releases/download/v$version"

cat <<FORMULA
# Generated by tools/brew-formula.sh. Do not edit by hand.
class Kalku < Formula
  desc "Mutation testing for humans, CI, and coding agents"
  homepage "https://github.com/lnds/kalku"
  version "$version"
  license any_of: ["MIT", "Apache-2.0"]

  on_macos do
    on_arm do
      url "$base/kalku-v$version-darwin-arm64.tar.gz"
      sha256 "$darwin_arm64"
    end
  end

  on_linux do
    on_intel do
      url "$base/kalku-v$version-linux-x86_64.tar.gz"
      sha256 "$linux_x86_64"
    end
  end

  def install
    bin.install "kalku", "kalku-kaikai", "kalku-rust"
  end

  test do
    assert_match "outcomes", shell_output("#{bin}/kalku info")
  end
end
FORMULA
